// strings-pt.js — a interface em português.
//
//   "revisa o app, organiza tudo varias coisas confusas"
//
// A tela vinha metade em inglês e metade em português: o título dizia "Bot de
// WhatsApp" e o corpo dizia "Not connected", a loja descrevia os apps em
// português dentro de cartas em inglês. Isso não é tradução pela metade, é
// desleixo, e quem lê sente.
//
// Toda chave aqui é a mesma que a view registra em inglês. O t() procura nesta
// tabela primeiro e cai no inglês quando falta alguma — então um app novo que
// ainda não passou por aqui aparece em inglês, e não quebrado.
//
// Uma palavra que fica: "helper"/"ajudante" já era português no código inteiro,
// da API aos agentes.

export const PT_BR = {
  'app.name': 'project-os',
  'shell.stream': 'Fluxo de eventos',
  'shell.theme': 'Tema',
  'shell.viewFailed': 'Esta tela não carregou',
  'shell.viewCrashed': 'Esta tela quebrou ao desenhar',
  'shell.appFailed': 'O {name} não conseguiu iniciar',
  'shell.appError': 'O aplicativo relatou um erro.',
  'nav.dashboard': 'Painel',
  'nav.apps': 'Aplicativos',
  'nav.devices': 'Aparelhos',
  'nav.settings': 'Configurações',
  'nav.system': 'Sistema',
  'nav.services': 'Serviços',
  'nav.files': 'Arquivos',
  'nav.terminal': 'Terminal',
  'nav.logs': 'Registros',
  'nav.helpers': 'Ajudantes',
  'nav.tuning': 'Hardware',
  'nav.packages': 'Programas',
  'nav.updates': 'Atualizações',
  'nav.store': 'Loja',
  'mode.simple': 'Simples',
  'mode.advanced': 'Avançado',
  'mode.label': 'Modo da interface',
  'theme.dark': 'Escuro',
  'theme.light': 'Claro',
  'theme.auto': 'Automático',
  'action.apply': 'Aplicar',
  'action.dismiss': 'Dispensar',
  'action.retry': 'Tentar de novo',
  'action.refresh': 'Atualizar',
  'action.cancel': 'Cancelar',
  'action.confirm': 'Confirmar',
  'action.save': 'Salvar',
  'action.close': 'Fechar',
  'action.logout': 'Sair',
  'action.back': 'Voltar',
  'action.continue': 'Continuar',
  'state.loading': 'Carregando…',
  'state.empty': 'Ainda não há nada aqui',
  'state.error': 'Deu algo errado',
  'state.offline': 'Desconectado',
  'state.connecting': 'Conectando…',
  'state.live': 'Ao vivo',
  'time.now': 'agora mesmo',
  'unit.cpu': 'CPU',
  'unit.ram': 'RAM',
  'unit.temp': 'Temp',
  'unit.disk': 'Disco',
  'unit.uptime': 'Ligado há',

  // ------------------------------------------------------------- primeiro uso
  'setup.title': 'Configurar o project-os',
  'setup.welcome.title': 'Bem-vindo ao project-os',
  'setup.welcome.lead': 'Esta máquina ainda não foi configurada. Leva um minuto.',
  'setup.welcome.point1': 'Crie uma conta de administrador para esta caixa.',
  'setup.welcome.point2': 'Depois o project-os procura caixas de som, TVs e centrais na sua rede.',
  'setup.welcome.point3': 'Os aplicativos que você instalar aparecem na lateral e no painel.',
  'setup.welcome.start': 'Começar',
  'setup.create.title': 'Crie a conta de administrador',
  'setup.create.lead': 'Esta é a única conta que existe até você criar outras.',
  'setup.username': 'Usuário',
  'setup.password': 'Senha',
  'setup.confirm': 'Confirme a senha',
  'setup.ssh': 'Usar esta senha no SSH também (o login de terminal desta máquina).',
  'setup.submit': 'Criar a conta',
  'setup.submitting': 'Criando…',
  'setup.needUser': 'Escolha um nome de usuário.',
  'setup.needPassword': 'Digite uma senha.',
  'setup.mismatch': 'As duas senhas não batem.',
  'setup.failed': 'Não deu para criar a conta.',
  'setup.keepSafe': 'Guarde esta senha em algum lugar seguro — numa Raspberry Pi não existe recuperação por e-mail.',
  'setup.strength.any': 'A senha que você quiser.',
  'setup.strength.weak': 'Fraca',
  'setup.strength.fair': 'Razoável',
  'setup.strength.good': 'Boa',
  'setup.strength.strong': 'Forte',
  'setup.strength.hint1': 'Curta, mas é sua.',
  'setup.strength.hint2': 'Comprida vale mais que complicada.',
  'setup.strength.hint3': 'Boa. Mais alguns caracteres não fariam mal.',
  'setup.strength.hint4': 'Forte.',
  'setup.done.title': 'Está tudo pronto',
  'setup.done.lead': 'Você entrou como {name}.',
  'setup.done.devices.title': 'Ache seus aparelhos',
  'setup.done.devices.text': 'O project-os procura na rede caixas de som AirPlay, Chromecasts, Home Assistant e outros. É de lá que o BirdTunes tira a saída de som.',
  'setup.done.apps.title': 'Depois escolha um aplicativo',
  'setup.done.apps.text': 'Os aplicativos são instalados pela loja e aparecem na lateral, cada um com a própria tela.',
  'setup.done.discover': 'Procurar aparelhos',
  'setup.done.dashboard': 'Ir para o painel',
  'setup.ssh.ready': 'O SSH está pronto com a mesma senha: ssh project-os@project-os.local',
  'setup.ssh.failed': 'A senha do SSH não foi configurada: {reason}',

  // ------------------------------------------------------------------ entrar
  'login.title': 'Entrar',
  'login.lead': 'Entre para cuidar desta máquina.',
  'login.username': 'Usuário',
  'login.password': 'Senha',
  'login.submit': 'Entrar',
  'login.submitting': 'Entrando…',
  'login.needBoth': 'Digite o usuário e a senha.',
  'login.wrong': 'Usuário ou senha errados.',
  'login.failed': 'Não deu para entrar.',

  // ------------------------------------------------------------------ painel
  'dash.lead': 'Tudo o que está rodando nesta máquina, de relance.',
  'dash.systemDetails': 'Detalhes do sistema',
  'dash.gotIt': 'Entendi',
  'dash.error.suggestions': 'Não deu para carregar as sugestões.',
  'dash.error.apply': 'Não deu para aplicar essa sugestão.',
  'dash.error.dismiss': 'Não deu para dispensar essa sugestão.',
  'dash.error.action': 'A ação falhou.',
  'dash.app.failed': 'Este aplicativo não conseguiu iniciar. Olhe os registros.',
  'dash.app.noStatus': 'Nada informado.',
  'dash.error.apps': 'Não deu para carregar os aplicativos.',
  'dash.apps.empty.title': 'Nenhum aplicativo rodando ainda',
  'dash.apps.empty.text': 'Instale um pela loja e ele aparece aqui com a própria carta.',
  'dash.apps.empty.action': 'Abrir a loja',
  'dash.error.devices': 'Não deu para carregar os aparelhos.',
  'dash.devices.all': 'Todos os aparelhos',
  'dash.devices.empty': 'Nada encontrado ainda',
  'dash.devices.scan': 'Procurar agora',
  'dash.devices.more': 'Todos os {count}',
  'dash.scan.started': 'Procurando na rede…',
  'dash.scan.failed': 'A busca falhou.',
  'dash.error.stats': 'Não deu para ler os números da máquina.',
  'dash.greeting.night': 'Boa madrugada',
  'dash.greeting.morning': 'Bom dia',
  'dash.greeting.afternoon': 'Boa tarde',
  'dash.greeting.evening': 'Boa noite',
  'dash.card.system': 'Sistema',
  'dash.card.apps': 'Aplicativos',
  'dash.card.devices': 'Aparelhos',
  'dash.card.suggestion': 'Sugestão',
  'dash.card.suggestions': 'Sugestões',
  'dash.up': 'No ar há {time}',
  'dash.yes': 'Sim',
  'dash.no': 'Não',
  'dash.action.install': 'Instalar',
  'dash.action.open': 'Abrir',
  'dash.action.apply': 'Aplicar',
  'dash.action.dismiss': 'Dispensar',
  'dash.action.run': 'Executar',
  'dash.action.done': 'Pronto',
  'dash.action.applied': 'Aplicado',
  'dash.action.scan': 'Procurar',

  // ------------------------------------------------------------- aplicativos
  'apps.lead': 'O que o project-os está rodando nesta máquina.',
  'apps.refresh': 'Atualizar',
  'apps.empty.title': 'Nada instalado ainda',
  'apps.empty.text': 'O project-os nasce vazio, de propósito — escolha algo na loja e ele aparece aqui com a própria tela.',
  'apps.empty.action': 'Abrir a loja',
  'apps.error.load': 'Não deu para carregar os aplicativos.',
  'apps.action.retry': 'Tentar de novo',
  'apps.action.start': 'Iniciar',
  'apps.action.stop': 'Parar',
  'apps.action.restart': 'Reiniciar',
  'apps.action.open': 'Abrir',
  'apps.action.openPort': 'Este app serve a tela dele na porta {port} desta máquina.',
  'apps.action.uninstall': 'Desinstalar',
  'apps.uninstall.confirm': 'Desinstalar {name}? As configurações e os dados ficam guardados, caso você instale de novo.',
  'apps.toast.uninstalled': '{name} desinstalado',
  'apps.toast.error': 'Isso não funcionou.',
  'apps.toast.action': '{action} · {name}',
  'apps.state.running': 'rodando',
  'apps.state.stopped': 'parado',
  'apps.state.starting': 'iniciando',
  'apps.state.error': 'erro',
  'apps.state.disabled': 'desligado',
  'apps.error.detail': 'Este aplicativo não conseguiu iniciar. Veja os registros dele na própria tela.',
  'detected.title': 'Também nesta máquina',
  'detected.lead': 'Programas que o project-os achou já instalados, fora dos aplicativos dele — apt, Flatpak, Snap, serviços do systemd e contêineres.',
  'detected.refresh': 'Verificar de novo',
  'detected.refreshing': 'Verificando…',
  'detected.cached': 'visto {time}',
  'detected.filter.all': 'Tudo',
  'detected.filter.package': 'Pacotes',
  'detected.filter.app': 'Aplicativos',
  'detected.filter.service': 'Serviços',
  'detected.filter.container': 'Contêineres',
  'detected.empty.title': 'Nada mais encontrado',
  'detected.empty.text': 'O project-os olhou apt, Flatpak, Snap, atalhos de área de trabalho, serviços do systemd e contêineres, e esta máquina não tem nada além dos aplicativos dele.',
  'detected.empty.filtered.title': 'Nada bate com este filtro',
  'detected.empty.filtered.text': 'Tente outra categoria, ou limpe o filtro para ver tudo o que foi achado.',
  'detected.error.load': 'Não deu para verificar o que está instalado nesta máquina.',
  'detected.col.name': 'Nome',
  'detected.col.version': 'Versão',
  'detected.col.source': 'Achado por',
  'detected.col.store': 'Loja',
  'detected.store.yes': 'Está na loja',
  'detected.also': '+{count} outros',
  'detected.notChecked': 'Não verificado: {list}',

  // ---------------------------------------------------------------- aparelhos
  'devices.lead': 'Tudo o que o project-os achou nesta rede.',
  'devices.rescan': 'Procurar agora',
  'devices.rescanning': 'Procurando…',
  'devices.scan.started': 'Procurando na rede…',
  'devices.scan.failed': 'A busca falhou.',
  'devices.filter.all': 'Todos',
  'devices.filter.online': 'Ligados',
  'devices.filter.pinned': 'Fixados',
  'devices.filter.ignored': 'Ignorados',
  'devices.filter.allKinds': 'Todos os tipos',
  'devices.empty.title': 'Nada encontrado ainda',
  'devices.empty.text': 'O project-os procura caixas de som AirPlay, Chromecasts, centrais e outras coisas por mDNS e sondagem local. Ligue alguma coisa e procure de novo.',
  'devices.empty.filtered.title': 'Nada bate com este filtro',
  'devices.empty.filtered.text': 'Limpe o filtro para ver o resto do que foi achado.',
  'devices.unavailable.title': 'A busca de aparelhos não está disponível',
  'devices.error.load': 'Não deu para carregar os aparelhos.',
  'devices.action.retry': 'Tentar de novo',
  'devices.action.pin': 'Fixar',
  'devices.action.unpin': 'Desafixar',
  'devices.action.ignore': 'Ignorar',
  'devices.action.unignore': 'Não ignorar',
  'devices.action.rename': 'Renomear',
  'devices.action.forget': 'Esquecer',
  'devices.action.save': 'Salvar',
  'devices.action.cancel': 'Cancelar',
  'devices.action.open': 'Abrir',
  'devices.rename.placeholder': 'Nome do aparelho',
  'devices.forget.confirm': 'Esquecer {name}? Ele volta na próxima busca, sem o nome que você deu.',
  'devices.toast.pinned': '{name} fixado',
  'devices.toast.unpinned': '{name} desafixado',
  'devices.toast.ignored': '{name} ignorado',
  'devices.toast.unignored': '{name} não está mais ignorado',
  'devices.toast.renamed': '{name} renomeado',
  'devices.toast.forgot': '{name} esquecido',
  'devices.toast.error': 'Isso não funcionou.',
  'devices.detail.back': 'Todos os aparelhos',
  'devices.detail.notfound.title': 'Aparelho não encontrado',
  'devices.detail.notfound.text': 'Pode ter sido esquecido, ou o endereço na barra está com o id errado.',
  'devices.detail.error.load': 'Não deu para carregar este aparelho.',
  'devices.detail.info.title': 'Detalhes',
  'devices.detail.info.address': 'Endereço',
  'devices.detail.info.kind': 'Tipo',
  'devices.detail.info.firstSeen': 'Visto pela primeira vez',
  'devices.detail.info.lastSeen': 'Visto por último',
  'devices.detail.info.capabilities': 'O que ele sabe fazer',
  'devices.detail.info.none': 'Nada informado',
  'devices.detail.info.properties': 'Propriedades cruas',
  'devices.detail.recipes.title': 'O que dá para fazer com este aparelho',
  'devices.detail.recipes.automatic': '{done} de {total} passos são um clique',
  'devices.detail.recipes.manualOnly': 'Aqui todo passo é manual — nada ainda pode ser feito por você.',
  'devices.detail.recipes.empty.title': 'Ainda não há receitas para este aparelho',
  'devices.detail.recipes.empty.text': 'O project-os ainda não conhece uma rotina específica para este tipo de aparelho.',
  'devices.detail.recipes.error': 'Não deu para carregar as receitas deste aparelho.',
  'devices.detail.step.manual': 'Manual',
  'devices.detail.step.blocked': 'ainda não',
  'devices.detail.step.run': 'Executar',
  'devices.detail.step.done': 'Feito',
  'devices.detail.step.open': 'Abrir',
  'devices.detail.step.apply': 'Aplicar',
  'devices.detail.step.install': 'Instalar',
  'devices.detail.step.installed': 'Instalado',
  'devices.status.online': 'ligado',
  'devices.status.offline': 'desligado',
  'devices.status.pinned': 'fixado',
  'devices.status.ignored': 'ignorado',

  // ----------------------------------------------------------------- sistema
  'sys.lead': 'Leituras ao vivo desta máquina. Tudo aqui é medido, nada é guardado.',
  'sys.card.host': 'Esta máquina',
  'sys.host.reading': 'Lendo o hardware…',
  'sys.host.model': 'Modelo',
  'sys.host.os': 'Sistema operacional',
  'sys.host.kernel': 'Kernel',
  'sys.host.arch': 'Arquitetura',
  'sys.host.cpu': 'CPU',
  'sys.host.memory': 'Memória',
  'sys.host.python': 'Python',
  'sys.host.addresses': 'Endereços',
  'sys.host.uptime': 'No ar há',
  'sys.host.load': 'Carga',
  'sys.host.pi': 'Raspberry Pi',
  'sys.host.generic': 'Máquina comum',
  'sys.card.processor': 'Processador',
  'sys.perCore': 'Por núcleo',
  'sys.perCore.none': 'Esta máquina não informa o uso por núcleo.',
  'sys.core': 'Núcleo {n}',
  'sys.card.memory': 'Memória',
  'sys.mem.ram': 'RAM',
  'sys.mem.swap': 'Swap',
  'sys.mem.used': 'Em uso',
  'sys.mem.available': 'Disponível',
  'sys.mem.cached': 'Em cache',
  'sys.card.thermal': 'Temperatura e energia',
  'sys.thermal.soc': 'Temperatura do chip',
  'sys.thermal.scale': 'Quente acima de 70 °C, começa a segurar perto de 80 °C',
  'sys.thermal.clean': 'Energia e temperatura estão limpas desde o boot.',
  'sys.thermal.viaVcgencmd': 'Os avisos de throttling vêm do vcgencmd e só existem no Raspberry Pi OS.',
  'sys.card.storage': 'Armazenamento',
  'sys.storage.none': 'Nenhum sistema de arquivos montado foi informado.',
  'sys.card.network': 'Rede',
  'sys.net.down': 'Baixando',
  'sys.net.up': 'Subindo',
  'sys.net.sinceBoot': 'Desde o boot',
  'sys.net.interfaces': 'Interfaces',
  'sys.net.samples': 'últimas {count} amostras',
  'sys.net.none': 'Nenhuma interface informada.',
  'sys.card.processes': 'Processos mais pesados',
  'sys.processes.sub': 'Ordenados por memória — o que acaba primeiro numa placa de 1 GB',
  'sys.processes.col.pid': 'PID',
  'sys.processes.col.name': 'Processo',
  'sys.processes.col.user': 'Dono',
  'sys.processes.col.cpu': 'CPU',
  'sys.processes.col.memory': 'Memória',
  'sys.processes.none': 'Nenhum processo informado.',
  'sys.processes.noPsutil': 'Esta instalação não informa o uso por processo. Instalar o psutil na Pi liga este quadro.',
  'sys.processes.showing': 'Mostrando os {shown} mais pesados de {total} processos.',
  'sys.processes.count': '{total} processos.',
  'sys.processes.cpuNote': 'Uso desde a última medição',
  'sys.error.info': 'Não deu para ler a descrição da máquina.',
  'sys.error.stats': 'Não deu para ler os números da máquina.',
  'sys.error.page': 'A tela de sistema não conseguiu carregar.',
  'sys.throttle.nowPower.title': 'Falta energia agora',
  'sys.throttle.nowPower.body': 'A placa está reclamando de subtensão. Use a fonte oficial deste modelo e um cabo USB curto e grosso — carregador de celular e cabo comprido são a causa de sempre.',
  'sys.throttle.nowCpu.title': 'A CPU está sendo segurada agora',
  'sys.throttle.nowCpu.body': 'O clock está sendo cortado para proteger o chip, então tudo fica lento. Veja a ventilação e a temperatura acima, ou resolva a fonte.',
  'sys.throttle.bootPower.title': 'Houve subtensão desde o boot',
  'sys.throttle.bootPower.body': 'A energia caiu pelo menos uma vez desde que a máquina ligou. Agora está bem, mas a fonte está no limite — é exatamente assim que cartão de memória corrompe.',
  'sys.throttle.bootCpu.title': 'A CPU foi segurada desde o boot',
  'sys.throttle.bootCpu.body': 'O chip bateu no limite pelo menos uma vez desde o boot — calor ou energia. Vale um dissipador ou uma fonte melhor se continuar acontecendo.',

  // ---------------------------------------------------------------- arquivos
  'files.title': 'Arquivos',
  'files.lead': 'Ver, editar e mover os arquivos que o project-os tem permissão de tocar.',
  'files.roots': 'Lugares permitidos',
  'files.readonly': 'A escrita está desligada nas Configurações (security.allow_file_write).',
  'files.readonly.link': 'Abrir Configurações › Desenvolvedor',
  'files.upload': 'Enviar',
  'files.newFolder': 'Nova pasta',
  'files.empty.title': 'Esta pasta está vazia',
  'files.empty.detail': 'Envie um arquivo ou crie uma pasta para começar.',
  'files.error.title': 'Não deu para listar esta pasta',
  'files.col.name': 'Nome',
  'files.col.size': 'Tamanho',
  'files.col.modified': 'Modificado',
  'files.action.download': 'Baixar',
  'files.action.rename': 'Renomear',
  'files.action.delete': 'Apagar',
  'files.action.edit': 'Editar',
  'files.rename.prompt': 'Novo nome para {name}',
  'files.mkdir.prompt': 'Nome da pasta',
  'files.confirm.delete': 'Apagar {name}? Isso não tem volta.',
  'files.confirm.deleteDir': 'Apagar {name} e tudo o que está dentro? Isso não tem volta.',
  'files.editor.title': 'Editando {name}',
  'files.editor.save': 'Salvar',
  'files.editor.saved': 'Salvo',
  'files.editor.tooLarge': 'Este arquivo é maior que o limite do editor; baixe ele em vez disso.',
  'files.editor.notText': 'Isto não parece um arquivo de texto.',
  'files.uploading': 'Enviando {name}…',
  'files.uploaded': '{name} enviado',
  'files.deleted': '{name} apagado',
  'files.permissionDenied': 'Permissão negada',

  // ---------------------------------------------------------------- ajudantes
  'helpers.title': 'Ajudantes',
  'helpers.lead': 'Outros computadores, placas e caixinhas dando uma mão para esta Pi — uma fila de tarefas inteiras, não processos compartilhados.',
  'helpers.section.paired': 'Ajudantes pareados',
  'helpers.section.pair': 'Parear um ajudante novo',
  'helpers.section.codes': 'Códigos em aberto',
  'helpers.section.jobs': 'Fila de tarefas',
  'helpers.empty.paired.title': 'Nenhum ajudante pareado ainda',
  'helpers.empty.paired.text': 'Quando um PC, outra Pi ou um ESP32 parear, ele aparece aqui com o que sabe fazer.',
  'helpers.empty.codes.title': 'Nenhum código esperando',
  'helpers.empty.codes.text': 'Gere um acima e ele fica aqui até ser usado ou vencer.',
  'helpers.empty.jobs.title': 'A fila está vazia',
  'helpers.empty.jobs.text': 'Tarefas passadas a um ajudante — uma conversão, um download, um ping de teste — aparecem aqui com o estado delas.',
  'helpers.error.load': 'Não deu para carregar a tela de ajudantes.',
  'helpers.online': 'Ligado',
  'helpers.offline': 'Desligado',
  'helpers.lastSeen': 'visto {time}',
  'helpers.neverSeen': 'nunca deu sinal',
  'helpers.offers': 'Oferece: {list}',
  'helpers.offersNone': 'Ainda não declarou nada',
  'helpers.rename': 'Renomear',
  'helpers.rename.prompt': 'Novo nome para {name}',
  'helpers.enable': 'Ligar',
  'helpers.disable': 'Desligar',
  'helpers.forget': 'Esquecer',
  'helpers.forget.title': 'Esquecer {name}?',
  'helpers.forget.detail': 'Isso não perde o trabalho — qualquer tarefa que ele esteja rodando volta para a fila e outro ajudante pega. Ele só deixa de estar pareado; parear de novo precisa de um código novo.',
  'helpers.forgotten': '{name} esquecido',
  'helpers.renamed': 'Renomeado para {name}',
  'helpers.enabled': '{name} ligado',
  'helpers.disabled': '{name} desligado',
  'helpers.kind.pc': 'Computador',
  'helpers.kind.pi': 'Raspberry Pi',
  'helpers.kind.esp32': 'ESP32',
  'helpers.kind.other': 'Aparelho desconhecido',
  'helpers.codes.new': 'Gerar código',
  'helpers.codes.kind.label': 'Restringir a',
  'helpers.codes.kind.any': 'Qualquer tipo',
  'helpers.codes.ttl.label': 'Vale por',
  'helpers.codes.ttl.10m': '10 minutos',
  'helpers.codes.ttl.30m': '30 minutos',
  'helpers.codes.ttl.1h': '1 hora',
  'helpers.codes.expiresIn': 'vence em {time}',
  'helpers.codes.expired': 'vencido',
  'helpers.codes.revoke': 'Cancelar',
  'helpers.codes.revoked': 'Código cancelado',
  'helpers.codes.copy.pc.title': 'Num Windows, macOS ou Linux',
  'helpers.codes.copy.pc.body': 'Copie {file} do repositório do project-os para essa máquina e rode:',
  'helpers.codes.copy.esp32.title': 'Num ESP32',
  'helpers.codes.copy.esp32.body': 'Grave o MicroPython, copie {file} como main.py e, antes de reiniciar, preencha:',
  'helpers.codes.copy.esp32.fields': 'WIFI_SSID, WIFI_PASSWORD, SERVER ({server}), PAIRING_CODE ({code}) e CAPABILITIES conforme o que estiver realmente ligado.',
  'helpers.codes.copied': 'Comando copiado',
  'helpers.jobs.submit': 'Mandar tarefa de teste',
  'helpers.act.read': 'Ler agora',
  'helpers.act.relayOn': 'Ligar o relé',
  'helpers.act.relayOff': 'desligar',
  'helpers.act.queued': 'Mandado para o {name}. Ele executa na próxima batida.',
  'helpers.fact.reading': 'leitura',
  'helpers.fact.button': 'botão',
  'helpers.fact.uptime': 'ligado há',
  'helpers.fact.ip': 'ip',
  'helpers.jobs.submit.hint': 'Uma tarefa "ping" não precisa de habilidade nenhuma — é o teste honesto de que um ajudante está mesmo pegando trabalho.',
  'helpers.jobs.submitted': 'Tarefa na fila',
  'helpers.jobs.noRunner': 'Está na fila, mas nenhum ajudante pareado oferece isso ainda — ela roda assim que algum oferecer.',
  'helpers.jobs.cancel': 'Cancelar',
  'helpers.jobs.cancelled': 'Tarefa cancelada',
  'helpers.jobs.state.queued': 'Na fila',
  'helpers.jobs.state.running': 'Rodando',
  'helpers.jobs.state.done': 'Pronta',
  'helpers.jobs.state.failed': 'Falhou',
  'helpers.jobs.state.cancelled': 'Cancelada',
  'helpers.jobs.col.kind': 'Tarefa',
  'helpers.jobs.col.state': 'Estado',
  'helpers.jobs.col.helper': 'Rodou em',
  'helpers.jobs.col.result': 'Resultado',
  'helpers.jobs.col.when': 'Enfileirada',
  'helpers.jobs.unassigned': '—',
  'helpers.stats.online': '{online} de {total} ligados',
  'helpers.badge.disabled': 'Desligado',
  'helpers.command.copy': 'Copiar',

  // ---------------------------------------------------------------- registros
  'logs.title': 'Registros',
  'logs.lead': 'As linhas de registro do sistema e dos aplicativos, ao vivo.',
  'logs.level.all': 'Todos os níveis',
  'logs.source.placeholder': 'Filtrar por origem (ex.: app.birdtunes)',
  'logs.search.placeholder': 'Procurar texto',
  'logs.pause': 'Pausar',
  'logs.resume': 'Continuar',
  'logs.copy': 'Copiar',
  'logs.copied': 'Copiado',
  'logs.clear': 'Limpar a tela',
  'logs.paused.notice': 'Atualização ao vivo pausada — as linhas novas estão sendo seguradas.',
  'logs.empty.title': 'Nenhuma linha bate com este filtro',
  'logs.empty.detail': 'Tente um nível ou uma origem mais abertos.',
  'logs.error.title': 'Não deu para carregar os registros',
  'logs.live': 'Ao vivo',
  'logs.offline': 'Sem atualização ao vivo',
  'logs.unit.badge': 'Registro de {unit}',
  'logs.unit.note': 'Estas linhas vêm do registro do sistema, não do project-os — elas não chegam sozinhas, recarregue para ver as novas.',
  'logs.unit.all': 'Todos os registros',
  'logs.unit.empty': 'O registro do sistema não tem nada dessa unidade',
  'logs.unit.empty.detail': 'Ou ela nunca subiu nesta máquina, ou as linhas dela já foram descartadas por idade.',
  'logs.reload': 'Recarregar',

  // ---------------------------------------------------------------- programas
  'packages.title': 'Programas',
  'packages.lead': 'Instalar programas nesta máquina. O que você instalar aqui aparece em Aplicativos.',
  'packages.search.placeholder': 'Procurar um programa — firefox, htop, vlc…',
  'packages.search.action': 'Procurar',
  'packages.search.hint': 'Pelo menos duas letras.',
  'packages.empty.title': 'Nada encontrado',
  'packages.empty.text': 'Tente outro nome. O apt casa com o nome do pacote, não com a descrição.',
  'packages.start.title': 'O que você quer instalar?',
  'packages.start.text': 'Procure acima. Os resultados vêm dos gerenciadores de pacote da própria máquina.',
  'packages.installed': 'Instalado',
  'packages.action.install': 'Instalar',
  'packages.action.remove': 'Remover',
  'packages.action.working': 'Trabalhando…',
  'packages.remove.confirm': 'Remover {name}? O que depender dele pode parar de funcionar.',
  'packages.disabled': 'Instalar está desligado. Ligue security.allow_package_management em Configurações › Desenvolvedor.',
  'packages.disabled.link': 'Abrir Configurações › Desenvolvedor',
  'packages.backends.title': 'Gerenciadores de pacote desta máquina',
  'packages.backend.ready': 'pronto',
  'packages.backend.unavailable': 'não dá para usar',
  'packages.skipped': '{source} foi pulado: {reason}',
  'packages.job.title': '{action} {package}',
  'packages.job.running': 'rodando',
  'packages.job.done': 'pronto',
  'packages.job.error': 'falhou',
  'packages.job.queued': 'na fila',
  'packages.jobs.recent': 'Recentes',
  'packages.error.load': 'Não deu para ler os gerenciadores de pacote.',
  'packages.action.retry': 'Tentar de novo',

  // ----------------------------------------------------------------- serviços
  'services.title': 'Serviços',
  'services.lead': 'Tudo o que o project-os pode iniciar, parar e reiniciar nesta máquina.',
  'services.units.title': 'Serviços gerenciados',
  'services.units.sub': 'unidades do systemd que o project-os conhece',
  'services.units.none': 'Nenhuma unidade gerenciada encontrada',
  'services.units.none.detail': 'O project-os só lista unidades com um prefixo conhecido (project_os, home-assistant, mosquitto e afins).',
  'services.units.unavailable': 'Não há systemd nesta máquina',
  'services.units.unavailable.detail': 'Isto parece uma máquina de desenvolvimento, não uma Pi — não há systemctl para perguntar.',
  'services.units.locked': 'O controle está desligado',
  'services.units.locked.detail': 'Ligue security.allow_service_control em Configurações para iniciar, parar ou reiniciar unidades daqui.',
  'services.units.locked.link': 'Abrir Configurações › Desenvolvedor',
  'services.apps.title': 'Aplicativos',
  'services.apps.sub': 'rodando dentro do próprio gerenciador do project-os',
  'services.apps.none': 'Nenhum aplicativo instalado',
  'services.apps.none.detail': 'Instale um pela loja e ele aparece aqui.',
  'services.action.start': 'Iniciar',
  'services.action.stop': 'Parar',
  'services.action.restart': 'Reiniciar',
  'services.action.logs': 'Registros',
  'services.confirm.stop': 'Parar {name}? O que depender dele perde a conexão.',
  'services.confirm.restart': 'Reiniciar {name}? Ele fica um instante fora do ar.',
  'services.up': 'no ar há {time}',

  // ------------------------------------------------------------ configurações
  'settings.lead': 'Como o project-os se comporta, e quem pode entrar.',
  'settings.section.general': 'Geral',
  'settings.section.account': 'Conta',
  'settings.section.network': 'Rede',
  'settings.section.integrations': 'Integrações',
  'settings.ha.title': 'Home Assistant',
  'settings.ha.sub': 'O que você já tem, não um segundo',
  'settings.ha.lead': 'O project-os não é feito em cima do Home Assistant e funciona sem ele. Se já existe um nesta rede, conectar nele é o jeito mais barato de alcançar aparelhos que o project-os teria que aprender um protocolo de cada vez.',
  'settings.ha.url': 'Endereço',
  'settings.ha.url.hint': 'Algo como homeassistant.local:8123 ou 192.168.1.20:8123. O http:// entra sozinho se você não puser.',
  'settings.ha.token': 'Token de acesso de longa duração',
  'settings.ha.token.hint': 'No Home Assistant: seu perfil, aba Segurança, lá embaixo — "Tokens de acesso de longa duração", Criar token. Ele só aparece uma vez.',
  'settings.ha.token.saved': 'Já tem um token salvo. Digite outro para trocar.',
  'settings.ha.test': 'Testar',
  'settings.ha.connect': 'Conectar',
  'settings.ha.disconnect': 'Desconectar',
  'settings.ha.disconnect.confirm.title': 'Esquecer este Home Assistant?',
  'settings.ha.disconnect.confirm.body': 'O project-os esquece o endereço e o token. Do lado do Home Assistant não muda nada, e o token continua valendo até você apagar lá.',
  'settings.ha.connected': 'Conectado',
  'settings.ha.notConnected': 'Sem conexão',
  'settings.ha.entities': 'Entidades',
  'settings.ha.entities.load': 'Ver o que tem lá',
  'settings.ha.entities.none': 'Este Home Assistant não relata entidade nenhuma.',
  'settings.ha.entities.more': 'e mais {count}',
  'settings.ha.on': 'Ligar',
  'settings.ha.off': 'Desligar',
  'settings.ha.needsHttpx': 'Esta integração precisa do pacote httpx, que não está instalado nesta caixa.',
  'settings.section.updates': 'Atualizações e sobre',
  'settings.section.developer': 'Desenvolvedor',
  'settings.error.load': 'Não deu para carregar as configurações.',
  'settings.action.retry': 'Tentar de novo',
  'settings.action.save': 'Salvar',
  'settings.action.saved': 'Salvo.',
  'settings.action.saveFailed': 'Não deu para salvar isso.',
  'settings.restartRequired': 'Isso passa a valer depois que o project-os reiniciar.',
  'settings.general.instanceName': 'Nome desta caixa',
  'settings.general.instanceName.hint': 'Como esta máquina se chama. Aparece na lateral e na aba do navegador — útil quando tem mais de uma.',
  'settings.general.theme': 'Tema',
  'settings.general.timezone': 'Fuso horário',
  'settings.general.timezone.hint': 'Decide a hora em que as coisas agendadas acontecem. O sistema pergunta o fuso à rede sozinho no primeiro boot.',
  'settings.general.timezone.detect': 'Usar o deste navegador',
  'settings.general.mode': 'Interface',
  'settings.general.mode.hint': 'O modo Simples é uma tela por assunto. O Avançado acrescenta sistema, serviços, arquivos, terminal e registros.',
  'settings.account.changePassword': 'Trocar a senha',
  'settings.account.currentPassword': 'Senha atual',
  'settings.account.newPassword': 'Senha nova',
  'settings.account.confirmPassword': 'Confirme a senha nova',
  'settings.account.password.empty': 'Digite a senha nova.',
  'settings.account.password.mismatch': 'A senha nova e a confirmação não batem.',
  'settings.account.password.changed': 'Senha trocada. Todas as sessões, inclusive esta, foram desconectadas — entre de novo.',
  'settings.account.sessions': 'Sessões abertas',
  'settings.account.sessions.empty': 'Não há outras sessões para mostrar.',
  'settings.account.sessions.revokeAll': 'Sair de todo lugar',
  'settings.account.sessions.revokeAll.confirm.title': 'Sair de todo lugar?',
  'settings.account.sessions.revokeAll.confirm.body': 'Todas as sessões são desconectadas, inclusive esta — você volta para a tela de entrar.',
  'settings.account.sessions.revoked': 'Todas as sessões foram desconectadas.',
  'settings.account.logout': 'Sair',
  'settings.account.anonymous': 'A autenticação está desligada, então não há conta para gerenciar aqui — a chave está em Desenvolvedor.',
  'settings.network.hostname': 'Nome na rede',
  'settings.network.host': 'Endereço de escuta',
  'settings.network.host.hint': '0.0.0.0 atende em todas as interfaces de rede. Precisa reiniciar depois de mudar.',
  'settings.network.port': 'Porta',
  'settings.network.discovery': 'Busca de aparelhos',
  'settings.network.discovery.hint': 'Deixa o project-os procurar aparelhos de casa inteligente e caixas de som na rede local (mDNS).',
  'settings.updates.version': 'Versão',
  'settings.updates.about': 'O project-os nasce vazio e cresce pela Loja — esta máquina não tem aplicativo nenhum até você adicionar por lá.',
  'settings.updates.docs': 'Documentação da API',
  'settings.developer.warning': 'Isto é para quem sabe o que está ligando. Nada aqui é necessário para usar o project-os.',
  'settings.developer.terminal': 'Deixar um terminal no canto',
  'settings.developer.terminal.hint': 'Prende um terminalzinho por cima de todas as telas — para instalar coisa na mão, olhar registro, o que for mais rápido num shell.',
  'settings.developer.card': 'Ferramentas de desenvolvedor',
  'settings.developer.terminal.needsShell': 'O acesso ao shell está desligado acima, então o terminal no canto não teria contra o que rodar.',
  'settings.developer.allowShell': 'Permitir acesso ao shell',
  'settings.developer.allowShell.hint': 'Deixa o project-os (e o terminal no canto) rodar comandos nesta máquina.',
  'settings.developer.verboseLogging': 'Registro detalhado',
  'settings.developer.verboseLogging.hint': 'Passa o nível do registro para DEBUG. Barulhento — desligue de novo assim que tiver o que queria.',
  'settings.developer.docsLink': 'Abrir /api/docs',
  'settings.developer.allowHardware': 'Permitir controlar o hardware',
  'settings.developer.allowHardware.hint': 'Destrava a tela de Ajustes de hardware: ventoinha, clock, LEDs, HDMI, economia de energia do Wi-Fi. Vem desligado porque um clock errado é uma das poucas coisas aqui que deixa a caixa precisando de teclado e monitor para voltar.',
  'settings.developer.allowServices': 'Permitir controlar serviços',
  'settings.developer.allowServices.hint': 'Destrava os botões Iniciar/Parar/Reiniciar da tela de Serviços, e os dois botões abaixo. Roda o systemctl como root.',
  'settings.developer.allowFileWrite': 'Permitir gravar arquivos',
  'settings.developer.allowFileWrite.hint': 'Deixa a tela de Arquivos salvar, enviar, renomear e apagar. Ler funciona de qualquer jeito.',
  'settings.developer.allowPackages': 'Permitir instalar programas',
  'settings.developer.allowPackages.hint': 'Deixa a tela de Programas instalar e remover software do sistema com o apt. Vem ligado — instalar coisa pelo navegador é o ponto do modo avançado.',
  'settings.developer.power': 'Energia',
  'settings.developer.power.sub': 'A placa em si, não só o project-os',
  'settings.developer.power.needsServices': 'O controle de serviços está desligado acima, então estes dois seriam recusados.',
  'settings.developer.reboot': 'Reiniciar a placa',
  'settings.developer.reboot.confirm.title': 'Reiniciar agora?',
  'settings.developer.reboot.confirm.body': 'A caixa some por mais ou menos um minuto. Esta página acha ela de novo sozinha quando voltar.',
  'settings.developer.reboot.sent': 'Reiniciando. Esta página volta sozinha.',
  'settings.developer.shutdown': 'Desligar',
  'settings.developer.shutdown.confirm.title': 'Desligar?',
  'settings.developer.shutdown.confirm.body': 'A placa se desliga. Só tirando e botando a energia de volta ela sobe de novo — não existe botão aqui para isso.',
  'settings.developer.shutdown.sent': 'Desligando. Espere a luz verde parar de piscar antes de tirar o cabo.',

  // --------------------------------------------------------------------- loja
  'store.lead': 'O project-os nasce vazio. Tudo abaixo é coisa que você pode acrescentar.',
  'store.category.automation': 'Automação',
  'store.category.camera': 'Câmeras',
  'store.category.dev': 'Desenvolvimento',
  'store.category.home': 'Casa',
  'store.category.media': 'Mídia',
  'store.category.network': 'Rede',
  'store.category.productivity': 'Produtividade',
  'store.category.server': 'Servidor',
  'store.category.storage': 'Armazenamento',
  'store.search.placeholder': 'Procurar aplicativos, categorias, etiquetas…',
  'store.filter.all': 'Tudo',
  'store.board.title': 'Esta máquina',
  'store.board.budget': '{free} livres para aplicativos',
  'store.board.reserved': '{mb} reservados para o próprio project-os',
  'store.board.tier.roomy': 'Sobra espaço',
  'store.board.tier.comfortable': 'Confortável',
  'store.board.tier.minimal': 'Apertado — escolha com cuidado',
  'store.empty.title': 'Nada bate',
  'store.empty.text': 'Tente outra busca ou outra categoria.',
  'store.error.load': 'Não deu para carregar a loja.',
  'store.action.retry': 'Tentar de novo',
  'store.action.started': 'Instalando o {name} pelo apt — acompanhe na tela de Programas.',
  'store.action.install': 'Instalar',
  'store.action.installing': 'Instalando…',
  'store.action.remove': 'Remover',
  'store.action.removing': 'Removendo…',
  'store.action.removed': '{name} removido. Os dados dele ficaram onde estavam.',
  'store.action.installed': '{name} está instalado.',
  'store.installed.badge': 'Instalado',
  'store.kind.builtin': 'Nativo',
  'store.kind.container': 'Contêiner',
  'store.kind.service': 'Serviço do sistema',
  'store.kind.recipe': 'Receita',
  'store.needs.ram': '{mb} MB de RAM',
  'store.needs.disk': '{mb} MB de disco',
  'store.needs.docker': 'Precisa de contêiner',
  'store.needs.usb': 'Precisa de um aparelho USB',
  'store.needs.node': 'Precisa do Node.js',
  'store.notice.noRuntime': 'Não achei Docker nem Podman nesta máquina — instale um antes que isto possa rodar.',
  'store.notice.pending': 'Isto instala como {kind}, e esse instalador ainda não está pronto. Clicar em Instalar não faz nada.',
  'store.notice.oversize': '{reason}',
  'store.confirm.oversize.title': 'Isto pode ser demais para esta placa',
  'store.confirm.oversize.body': 'Instalar mesmo assim?',
  'store.confirm.oversize.confirm': 'Instalar mesmo assim',
  'store.confirm.remove.title': 'Remover {name}?',
  'store.confirm.remove.body': 'Ele para de rodar. As configurações e os dados ficam no disco — reinstalar traz tudo de volta.',
  'store.confirm.remove.confirm': 'Remover',
  'store.state.starting': 'iniciando…',
  'store.state.running': 'rodando',
  'store.state.error': 'não iniciou',
  'store.state.stopped': 'parado',
  'store.toast.error': 'Isso não funcionou.',

  // ----------------------------------------------------------------- terminal
  'terminal.title': 'Terminal',
  'terminal.lead': 'Um shell de verdade nesta máquina. Tudo o que você digitaria num SSH funciona aqui.',
  'terminal.disabled': 'O terminal está desligado',
  'terminal.disabled.detail': 'Ligue security.allow_shell nas Configurações para usar.',
  'terminal.noPty': 'Não há pty disponível nesta máquina',
  'terminal.connecting': 'Conectando…',
  'terminal.connected': 'Conectado',
  'terminal.disconnected': 'Desconectado',
  'terminal.reconnect': 'Reconectar',
  'terminal.clear': 'Limpar',
  'terminal.interrupt': 'Mandar Ctrl-C',
  'terminal.placeholder': 'Digite um comando e aperte Enter',
  'terminal.limitation': 'Programas de tela cheia (top, vim, less) saem embaralhados — aqui não há emulador de terminal, só o texto corrido.',
  'terminal.exited': 'O shell terminou.',
  'terminal.ready': '{shell} (pid {pid})',
  'terminal.unauthenticated': 'Você não está conectado.',

  // ----------------------------------------------------------------- hardware
  'tuning.title': 'Ajustes de hardware',
  'tuning.lead': 'Os botões da própria placa. As mudanças marcadas com "no boot" são escritas no config.txt e só valem depois de reiniciar.',
  'tuning.error.load': 'Não deu para ler a tela de ajustes de hardware.',
  'tuning.disabled.title': 'O controle de hardware está desligado',
  'tuning.disabled.text': 'Ligue security.allow_hardware_control em Configurações › Desenvolvedor para mexer na ventoinha, no clock ou nos LEDs daqui. Ler continua funcionando sem isso.',
  'tuning.disabled.link': 'Abrir Configurações › Desenvolvedor',
  'tuning.notRoot.title': 'Daqui, só leitura',
  'tuning.notRoot.text': 'O project-os não está rodando como root, então dá para ler estes valores mas não para mudar. O serviço do systemd roda como root; um venv aberto na mão pelo terminal, não.',
  'tuning.section.fan': 'Ventoinha',
  'tuning.fan.unavailable': 'Nenhuma ventoinha que o kernel controle',
  'tuning.fan.level': 'Nível atual',
  'tuning.fan.setLevel': 'Mudar o nível agora',
  'tuning.fan.levelNote': 'Temporário — a curva do próprio firmware desmancha isso assim que a temperatura muda. Para deixar a ventoinha quieta de verdade, suba os limites abaixo.',
  'tuning.fan.curve': 'Limites de acionamento (no boot)',
  'tuning.fan.curve.step': 'Degrau {n}',
  'tuning.fan.curve.celsius': '°C',
  'tuning.fan.curve.speed': 'velocidade',
  'tuning.fan.curve.save': 'Salvar a curva',
  'tuning.fan.curve.add': 'Adicionar passo',
  'tuning.fan.curve.empty': 'Este card está vazio porque o config.txt ainda não tem nenhuma temperatura de ventoinha — a placa está usando a curva padrão do firmware.',
  'tuning.fan.curve.hint': 'Até quatro passos: em cada temperatura a ventoinha pula para aquela velocidade (0 a 255). Temperatura mais alta é caixa mais quieta e chip mais quente; o Pi se segura sozinho muito antes de qualquer estrago.',
  'tuning.fan.levelSet': 'Ventoinha em {level}/{max}',
  'tuning.fan.curveSaved': 'Curva salva — passa a valer no próximo boot',
  'tuning.section.clock': 'Clock da CPU',
  'tuning.clock.unavailable': 'Esta máquina não expõe cpufreq',
  'tuning.clock.current': 'Agora',
  'tuning.clock.range': 'Faixa',
  'tuning.clock.governor': 'Governador',
  'tuning.clock.governorSet': 'Governador mudado para {name}',
  'tuning.clock.maxClock': 'Teto de clock no boot',
  'tuning.clock.maxClock.hint': 'Deixe em branco para a velocidade de fábrica. Não tem ajudante de overclock aqui de propósito — passar do padrão também pede mais tensão e um dissipador de verdade, decisões que um controle deslizante não deveria tomar sem querer.',
  'tuning.clock.maxClock.save': 'Salvar o teto',
  'tuning.clock.maxClock.saved': 'Teto salvo — passa a valer no próximo boot',
  'tuning.clock.maxClock.cleared': 'Teto removido — volta ao de fábrica no próximo boot',
  'tuning.section.leds': 'LEDs',
  'tuning.leds.empty': 'Nenhum LED controlável encontrado',
  'tuning.leds.on': 'Ligado',
  'tuning.leds.off': 'Desligado',
  'tuning.leds.trigger': 'Gatilho',
  'tuning.leds.updated': '{name} atualizado',
  'tuning.section.hdmi': 'Saída HDMI',
  'tuning.hdmi.unavailable': 'O vcgencmd não está disponível nesta máquina',
  'tuning.hdmi.on': 'Saída ligada',
  'tuning.hdmi.off': 'Saída desligada',
  'tuning.hdmi.updated': 'Saída HDMI {state}',
  'tuning.section.wifi': 'Economia de energia do Wi-Fi',
  'tuning.wifi.unavailable': 'Nenhuma interface Wi-Fi encontrada',
  'tuning.wifi.hint': 'Tudo o que espera ser encontrado — esta página inclusive — quer a economia desligada. Um sensor que só manda dados quer ligada.',
  'tuning.wifi.updated': 'Economia de energia da {interface} {state}',
  'tuning.section.gpu': 'Divisão de memória da GPU',
  'tuning.gpu.current': 'Agora',
  'tuning.gpu.boot': 'No boot',
  'tuning.gpu.note': 'Numa caixa sem monitor, 16 MB bastam e o resto volta para os aplicativos.',
  'tuning.gpu.save': 'Salvar a divisão',
  'tuning.gpu.saved': 'Divisão de memória salva — passa a valer no próximo boot',
  'tuning.reboot.title': 'Isto precisa de reinício',
  'tuning.reboot.detail': 'Isto é escrito no config.txt e só passa a valer depois que a placa reiniciar — não muda nada agora.',
  'tuning.temporary.badge': 'agora, temporário',
  'tuning.reboot.badge': 'no boot',
  'tuning.notAvailableShort': 'Não existe neste hardware',

  // ------------------------------------------------------------ atualizações
  'updates.title': 'Atualizações',
  'updates.lead': 'Puxar uma versão nova pela rede. Sem cartão de memória, sem computador.',
  'updates.current': 'Esta máquina está na',
  'updates.method.git': 'Atualiza por git (instalado de um clone)',
  'updates.method.tarball': 'Atualiza por um manifesto de versão',
  'updates.check': 'Procurar atualização',
  'updates.checking': 'Procurando…',
  'updates.uptodate': 'Está em dia.',
  'updates.available': 'A versão {version} está disponível.',
  'updates.install': 'Instalar a {version}',
  'updates.installing': 'Instalando…',
  'updates.restarting': 'Reiniciando na versão nova…',
  'updates.back': 'De volta na {version}.',
  'updates.confirm': 'Atualizar para a {version}? O project-os vai reiniciar. Os aplicativos param por alguns segundos; seus dados não são tocados.',
  'updates.notes': 'O que mudou',
  'updates.source': 'De onde vem a atualização',
  'updates.error.check': 'Não deu para procurar atualização.',
  'updates.rollback': 'Voltar para a versão anterior',

  // Os dois sistemas do cartão -- docs/RECOVERY.md.
  'sys.title': 'Sistema do cartão',
  'sys.sub': 'Dois sistemas: um rodando, outro de reserva',
  'sys.running': 'Rodando agora',
  'sys.target': 'A atualização vai para',
  'sys.good': 'Último que se provou bom',
  'sys.slot': 'Sistema {slot}',
  'sys.explain': 'A atualização é gravada no sistema que não está rodando. Se ele não subir, a caixa volta sozinha para este aqui — sem tirar o cartão.',
  'sys.available': 'Sistema {version} disponível',
  'sys.install': 'Instalar o sistema {version}',
  'sys.confirm': 'Gravar o sistema {version} no cartão e reiniciar? O sistema que está rodando agora fica intacto como reserva.',
  'sys.rollback': 'Reiniciar no sistema {slot}',
  'sys.rollback.confirm': 'Reiniciar no sistema {slot}? Use isto se o sistema atual subiu mas está pior.',
  'sys.rollback.started': 'Reiniciando no outro sistema.',
  'sys.unavailable': 'Este cartão tem um sistema só.',
  'updates.disabled': 'As atualizações estão desligadas nas configurações.',
  'updates.log': 'Registro',
  'updates.blocked': 'Esta caixa não troca o app por conta própria.',

  // ---------------------------------------------------------------- BirdTunes
  'bt.title': 'BirdTunes',
  'bt.now_playing': 'Tocando agora',
  'bt.nothing_playing': 'Nada tocando',
  'bt.play': 'Tocar',
  'bt.pause': 'Pausar',
  'bt.resume': 'Continuar',
  'bt.stop': 'Parar',
  'bt.next': 'Próxima',
  'bt.quiet_hours': 'Horário de silêncio — o BirdTunes não toca agora.',
  'bt.next_change': 'Depois',
  'bt.section.output': 'Onde toca',
  'bt.output.backend': 'Conexão',
  'bt.output.device': 'Caixa de som',
  'bt.output.none': 'Não escolhida',
  'bt.output.empty': 'Nenhuma caixa de som achada ainda. Procure aparelhos na tela Aparelhos.',
  'bt.output.pair': 'Parear',
  'bt.output.pin': 'PIN que aparece na caixa',
  'bt.output.pin.send': 'Confirmar o PIN',
  'bt.output.paired': 'Pareado.',
  'bt.output.volume': 'Volume',
  'bt.section.library': 'Acervo',
  'bt.library.empty': 'Nenhuma faixa ainda. Traga do YouTube aqui embaixo, ou jogue arquivos na pasta de mídia e procure.',
  'bt.library.scan': 'Procurar arquivos',
  'bt.library.scanned': 'Busca terminada: %d novas, %d que já existiam.',
  'bt.library.like': 'Gostei',
  'bt.library.less': 'Tocar menos',
  'bt.library.block': 'Nunca tocar',
  'bt.library.unblock': 'Liberar de novo',
  'bt.library.play': 'Tocar esta',
  'bt.library.liked': 'Curtida',
  'bt.library.lessened': 'Vai aparecer menos.',
  'bt.library.blocked': 'Bloqueada',
  'bt.library.missing': 'arquivo sumiu',
  'bt.section.compat': 'Compatibilidade',
  'bt.compat.ok': 'Todas as faixas tocam na saída atual.',
  'bt.compat.warn': '%d de %d faixas não tocam nesta saída.',
  'bt.compat.convert': 'Converter para MP3',
  'bt.compat.no_ffmpeg': 'Instale o ffmpeg para converter as faixas incompatíveis.',
  'bt.section.playlists': 'Playlists',
  'bt.playlists.empty': 'Nenhuma playlist ainda.',
  'bt.playlists.new': 'Playlist nova',
  'bt.playlists.name': 'Nome da playlist',
  'bt.playlists.create': 'Criar',
  'bt.playlists.play': 'Tocar agora',
  'bt.playlists.delete': 'Apagar',
  'bt.playlists.tracks': 'faixas',
  'bt.playlists.track': 'faixa',
  'bt.state.idle': 'parado',
  'bt.state.playing': 'tocando',
  'bt.state.paused': 'pausado',
  'bt.state.connecting': 'conectando',
  'bt.state.stopped': 'parado',
  'bt.section.import': 'Trazer do YouTube',
  'bt.import.url': 'Link de vídeo ou playlist',
  'bt.import.preview': 'Espiar',
  'bt.import.start': 'Trazer',
  'bt.import.found': 'Achei: %s (%d itens)',
  'bt.import.no_ytdlp': 'O yt-dlp não está instalado. Não dá para trazer do YouTube.',
  'bt.import.jobs.empty': 'Nada trazido ainda.',
  'bt.import.cast': 'Tocar direto na TV (sem baixar)',
  'bt.import.cast.hint': 'Toca pelo aplicativo de YouTube da própria televisão, então o YouTube passa a propaganda dele. Para ouvir sem propaganda, use Trazer: o áudio fica guardado aqui e o BirdTunes toca.',
  'bt.import.dest': 'Guardar em',
  'bt.import.dest.library': 'Só no acervo',
  'bt.import.dest.new': 'Playlist nova a partir deste link',
  'bt.import.queued': 'Baixando. Cai no acervo quando terminar.',
  'bt.library.add.url': 'Link do YouTube',
  'bt.library.add': 'Trazer',
  'bt.playlists.add.youtube': 'Trazer do YouTube',
  'bt.import.cast.ok': 'Tocando em %s.',
  'bt.playlists.add': 'Pôr numa playlist',
  'bt.playlists.added': 'Foi para %s.',
  'bt.section.schedule': 'Agenda',
  'bt.schedule.enabled': 'Agenda ligada',
  'bt.schedule.quiet_start': 'Silêncio começa',
  'bt.schedule.quiet_end': 'Silêncio termina',
  'bt.schedule.windows.empty': 'Nenhum horário ainda — crie um ou use um pronto aqui embaixo.',
  'bt.schedule.windows': 'Quando toca',
  'bt.schedule.presets': 'Começar de um pronto',
  'bt.schedule.add': 'Criar um horário',
  'bt.schedule.remove': 'Apagar este horário',
  'bt.schedule.window.name': 'Nome',
  'bt.schedule.window.from': 'Das',
  'bt.schedule.window.to': 'Às',
  'bt.schedule.window.days': 'Dias',
  'bt.schedule.window.playlist': 'Toca',
  'bt.schedule.window.on': 'Ligado',
  'bt.schedule.window.off': 'Desligado',
  'bt.schedule.days.short': 'Seg Ter Qua Qui Sex Sáb Dom',
  'bt.schedule.quiet.hint': 'O BirdTunes nunca toca entre esses dois horários, mesmo que a agenda mande.',
  'bt.schedule.save': 'Salvar a agenda',
  'bt.save.ok': 'Salvo',
  'bt.save.failed': 'Não deu para salvar',
  'bt.action.failed': 'A ação falhou',

  // ------------------------------------------------------------ bot WhatsApp
  'wa.title': 'Bot de WhatsApp',
  'wa.provider': 'Por onde conecta',
  'wa.provider.null': 'Nenhum (só registra)',
  'wa.provider.cloud_api': 'Cloud API (Meta)',
  'wa.provider.bridge': 'Ponte local',
  'wa.status.connected': 'Conectado',
  'wa.status.notconnected': 'Não conectado',
  'wa.status.unknown': 'Ainda não conferido',
  'wa.status.checking': 'Conferindo…',
  'wa.status.recheck': 'Conferir conexão',
  'wa.status.reason': 'Motivo',
  'wa.save': 'Salvar',
  'wa.section.connection': 'Conexão',
  'wa.section.allowlist': 'Contatos liberados',
  'wa.section.messages': 'Mensagens recentes',
  'wa.section.send': 'Mandar uma mensagem de teste',
  'wa.section.pairing': 'Pareamento da ponte',
  'wa.allowlist.empty': 'Nenhum contato liberado ainda. O bot ignora todo mundo até você pôr um número aqui.',
  'wa.allowlist.add': 'Pôr um número',
  'wa.allowlist.placeholder': 'ex.: 5511912345678',
  'wa.allowlist.added': 'Número adicionado',
  'wa.allowlist.removed': 'Número removido',
  'wa.messages.empty': 'Nenhuma mensagem ainda.',
  'wa.messages.in': 'entrou',
  'wa.messages.out': 'saiu',
  'wa.send.to': 'Para',
  'wa.send.text': 'Mensagem',
  'wa.send.button': 'Mandar',
  'wa.send.sent': 'Mensagem enviada',
  'wa.send.logged': 'Nada foi enviado: nenhum provedor conectado',
  'wa.send.failed': 'Não deu para mandar',
  'wa.cloud.phone_number_id': 'phone_number_id',
  'wa.cloud.access_token': 'access_token',
  'wa.cloud.verify_token': 'verify_token',
  'wa.cloud.app_secret': 'app_secret',
  'wa.bridge.base_url': 'Endereço da ponte',
  'wa.bridge.token': 'Token da ponte',
  'wa.commands.prefix': 'Prefixo dos comandos',
  'wa.rate_limit': 'Máximo de mensagens por minuto por contato',
  'wa.pairing.hint': 'Abra os registros do contêiner da ponte (ou o endereço do QR) e leia com o WhatsApp em Aparelhos conectados.',
  'wa.save.ok': 'Configurações salvas',
  'wa.save.failed': 'Não deu para salvar as configurações',
};

export default PT_BR;
